logger: none
name: fm_cms_pow_evt_net 
sigma: 0.0001
n_steps: 25
train_type: evt
flow_type: fm

# num_epochs: 500
num_epochs: 10
learningrate: 3e-5
opt: lion
loss_type: mse

lr_scheduler: true
use_swa: true
check_val_every_n_epoch: 1
gradient_clip_val: 1.0
truth_binary_class: false


# reduce_ds_train: 2_800_000
# reduce_ds_valid: 35000
# reduce_ds_train: 300000
# reduce_ds_valid: 50000
# eval_num_events: 50000

reduce_ds_train: 795000
reduce_ds_valid: 99000
eval_num_events: 99916

entry_start_train: 0
# entry_start_valid: 2_800_000
# entry_start_test: 0
# entry_start_valid: 300000
# entry_start_test: 350000
entry_start_valid: 795000
entry_start_test: 894000


num_workers: 6
batchsize: 128
val_batchsize: 5000

# eval_dir: /storage/agrp/dmitrykl/fastsim/FS_evals/
eval_dir: /global/cfs/cdirs/m3246/ylo/parnassus-hep/cms-flow-evt/evals/
# truth_path_train: /storage/agrp/dmitrykl/fastsim/f_delphes/data/full_event/output/QCD_Pt-470to600_TTbar_Merged/merged_train_v2_pt025_eta27_ghost.root
truth_path_train: my_sample/Parnussus_ntuple_QCD_Pt-35toInf_merge_filter_class5.root
# truth_path_valid: /storage/agrp/dmitrykl/fastsim/f_delphes/data/full_event/output/QCD_Pt-470to600_TTbar_Merged/merged_train_v2_pt025_eta27_ghost.root
truth_path_valid: my_sample/Parnussus_ntuple_QCD_Pt-35toInf_merge_filter_class5.root
# truth_path_test: /storage/agrp/dmitrykl/fastsim/f_delphes/data/full_event/output/QCD_Pt-600to800_TuneZ2_7TeV_pythia6/merged_test_small_v2_pt025_eta27_ghost.root
truth_path_test: my_sample/Parnussus_ntuple_QCD_Pt-35toInf_merge_filter_class5.root

max_particles: 400
time_pow: true
use_global: true

hidden_dim: 128
global_dim: 16
n_res_blocks: 3

act: gelu

var_transform: !include var_transform_ttbar_qcd.yaml

truth_variables:
    - truth_pt
    - truth_eta
    - truth_phi
    - truth_vx
    - truth_vy
    - truth_vz
    - truth_class
    
pflow_variables:
    - pflow_pt
    - pflow_eta
    - pflow_phi
    - pflow_vx
    - pflow_vy
    - pflow_vz
    - pflow_class
